---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: managed-kubernetes-definitions
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-gcp-provider
  # - name: crossplane-aws-provider
  # - name: crossplane-azure-provider
  interval: 1m0s
  path: ./infra-blueprints/deployment-artifacts/kubernetes-xrds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system