apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: kubernetesclusters.platform.com
spec:
  connectionSecretKeys:
  - kubeconfig
  group: platform.com
  names:
    kind: KubernetesCluster
    plural: kubernetesclusters
  claimNames:
    kind: KubernetesClusterClaim
    plural: kubernetesclusterclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Cluster ID that other objects refer to
              parameters:
                type: object
                properties:
                  version:
                    description: Supported by provider Kubernetes version
                    type: string
                  region:
                    description: Cloud region for provisioned resources
                    type: string
                    default: use1
                  nodeSize:
                    description: The node's size; supported; small, medium, large
                    type: string
                    default: small
                  nodeCount:
                    description: The desired number of nodes
                    type: integer
                    default: 1
                  fargateNamespace:
                    description: The Namespace for Fargate Profile
                    type: string
                    default: default
                required:
                - version
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The cluster name
                type: string
              controlPlaneStatus:
                description: The control plane status
                type: string
              nodePoolStatus:
                description: The node pool status
                type: string
              fargateProfileStatus:
                description: The Fargate Profile status
                type: string
              gatewayid:
                description: dummy to get InternetGatewayID and patch it to RouteTable
                type: string
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: ".status.clusterName"
    - name: controlPlane
      type: string
      jsonPath: ".status.controlPlaneStatus"
    - name: nodePool
      type: string
      jsonPath: ".status.nodePoolStatus"
